version: "3.8"

# docker-compose up --build

services:
  eco-device-app:
    image: eco-device-app
    container_name: eco-device-app
    build:
      context: .
      dockerfile: Dockerfile.test
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      # - ~/Dev/eco-device/src:/code
      - ~/eco-devices:/home/eco-devices
