version: "3.8"

# docker-compose up --build

services:
  eco-device-app:
    image: eco-device-app
    container_name: eco-device-app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: unless-stopped
    volumes:
      - ~/eco-devices:/home/eco-devices
      # Set the container localtime based on host
      - /etc/localtime:/etc/localtime
